name: architecture_reservation_app
description: A Flutter app for architecture design reservations.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1

flutter:
  uses-material-design: true